# Generated by Django 4.2.5 on 2024-03-30 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='todo.task'),
        ),
    ]
